using System.Text;
using Microsoft.CodeAnalysis.Text;
using ProtobufSourceGenerator.Incremental;
using VerifyCS = ProtobufSourceGenerator.Tests.Incremental.CSharpIncrementalSourceGeneratorVerifier<ProtobufSourceGenerator.Incremental.IncrementalSourceGenerator>;

namespace ProtobufSourceGenerator.Tests.Incremental;

public class IncrementalSourceGeneratorTests
{
    private const string CRLF = "\r\n";

    [Fact]
    public async Task SinglePropertyTest()
    {
        var code = @"namespace Test;

[ProtoBuf.ProtoContract]
public partial class Entity
{
    public int Id { get; set; }
}";

        var generated = @"// <auto-generated/>
#nullable enable
namespace Test;
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public partial class Entity
{
    [global::ProtoBuf.ProtoMember(1)]
    private int ProtoId { get => Id; set => Id = value; }
}";
        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(IncrementalSourceGenerator), "ProtoEntity.g.cs", SourceText.From(generated.ReplaceLineEndings(CRLF), Encoding.UTF8, SourceHashAlgorithm.Sha1)),
                },
            },
        };
        await test.RunAsync();
    }

    [Fact]
    public async Task WithRecordTypesClasses()
    {
        var code = @"namespace Test;

[ProtoBuf.ProtoContract]
public partial class Entity
{
    public int Id { get; set; }
}

public record SomeEntity
{
    public int Id { get; set; }
}";

        var generated = @"// <auto-generated/>
#nullable enable
namespace Test;
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public partial class Entity
{
    [global::ProtoBuf.ProtoMember(1)]
    private int ProtoId { get => Id; set => Id = value; }
}";
        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(IncrementalSourceGenerator), "ProtoEntity.g.cs", SourceText.From(generated.ReplaceLineEndings(CRLF), Encoding.UTF8, SourceHashAlgorithm.Sha1)),
                },
            },
        };
        await test.RunAsync();
    }

    [Fact]
    public async Task WithNonGeneratingInnerClass()
    {
        var code = @"namespace Test;

[ProtoBuf.ProtoContract]
public partial class Entity
{
    public class SomeEntity
    {
        public int Id { get; set; }
    }

    public int Id { get; set; }
}";

        var generated = @"// <auto-generated/>
#nullable enable
namespace Test;
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public partial class Entity
{
    [global::ProtoBuf.ProtoMember(1)]
    private int ProtoId { get => Id; set => Id = value; }
}";

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(IncrementalSourceGenerator), "ProtoEntity.g.cs", SourceText.From(generated.ReplaceLineEndings(CRLF), Encoding.UTF8, SourceHashAlgorithm.Sha1)),
                },
            },
        };
        await test.RunAsync();
    }

    [Fact]
    public async Task WithGeneratingInnerClasses()
    {
        var code = @"namespace Test;

[ProtoBuf.ProtoContract]
public partial class Entity
{
    [ProtoBuf.ProtoContract]
    public partial class SomeEntity
    {
        public int Id { get; set; }
    }

    public int Id { get; set; }
}";

        var generatedEntity = @"// <auto-generated/>
#nullable enable
namespace Test;
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public partial class Entity
{
    [global::ProtoBuf.ProtoMember(1)]
    private int ProtoId { get => Id; set => Id = value; }
}";

        var generatedSomeEntity = @"// <auto-generated/>
#nullable enable
namespace Test;
public partial class Entity
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
    public partial class SomeEntity
    {
        [global::ProtoBuf.ProtoMember(1)]
        private int ProtoId { get => Id; set => Id = value; }
    }
}";

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(IncrementalSourceGenerator), "ProtoEntity.g.cs", SourceText.From(generatedEntity.ReplaceLineEndings(CRLF), Encoding.UTF8, SourceHashAlgorithm.Sha1)),
                    (typeof(IncrementalSourceGenerator), "ProtoSomeEntity.g.cs", SourceText.From(generatedSomeEntity.ReplaceLineEndings(CRLF), Encoding.UTF8, SourceHashAlgorithm.Sha1)),
                },
            },
        };

        await test.RunAsync();
    }

    [Fact]
    public async Task WithGeneratingInner_NonGeneratingParentClass()
    {
        var code = @"namespace Test;
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public class Entity
{
    [ProtoBuf.ProtoContract]
    public partial class SomeEntity
    {
        public int Id { get; set; }
    }

    public int Id { get; set; }
}";

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                },
            },
        };

        await test.RunAsync();
    }

    [Fact]
    public async Task InitOnlyProperties_DoNotGenerate()
    {
        var code = @"namespace Test;
[ProtoBuf.ProtoContract]
public partial class Entity
{
    public int Id { get; init; }
}";

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                },
            },
        };

        await test.RunAsync();
    }

    [Fact]
    public async Task NullabeReferenceTypesProperties()
    {
        var code = @"#nullable enable
namespace Test;
[ProtoBuf.ProtoContract]
public partial class Entity
{
    public string? Id { get; set; }
}";

        var generated = @"// <auto-generated/>
#nullable enable
namespace Test;
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public partial class Entity
{
    [global::ProtoBuf.ProtoMember(1)]
    private string? ProtoId { get => Id; set => Id = value; }
}";

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(IncrementalSourceGenerator), "ProtoEntity.g.cs", SourceText.From(generated.ReplaceLineEndings(CRLF), Encoding.UTF8, SourceHashAlgorithm.Sha1)),
                },
            },
        };

        await test.RunAsync();
    }

    [Fact]
    public async Task NullabeGenericReferenceTypesProperties()
    {
        var code = @"#nullable enable
namespace Test;
[ProtoBuf.ProtoContract]
public partial class Entity
{
    public System.Collections.Generic.List<string?> Id { get; set; } = new();
}";

        var generated = @"// <auto-generated/>
#nullable enable
namespace Test;
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public partial class Entity
{
    [global::ProtoBuf.ProtoMember(1)]
    private System.Collections.Generic.List<string?> ProtoId { get => Id; set => Id = value; }

    [global::ProtoBuf.ProtoMember(2)]
    private bool ProtoIsEmptyId
    {
        get => ProtoId?.Count == 0;
        set
        {
            if (value)
                ProtoId = new();
        }
    }
}";

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(IncrementalSourceGenerator), "ProtoEntity.g.cs", SourceText.From(generated.ReplaceLineEndings(CRLF), Encoding.UTF8, SourceHashAlgorithm.Sha1)),
                },
            },
        };

        await test.RunAsync();
    }

    [Fact]
    public async Task NullabeValueTypesWithNullableReferenceTypesProperties()
    {
        var code = @"#nullable enable
namespace Test;
[ProtoBuf.ProtoContract]
public partial class Entity
{
    public System.Collections.Generic.List<int?>? Id { get; set; } = new();
}";

        var generated = @"// <auto-generated/>
#nullable enable
namespace Test;
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public partial class Entity
{
    [global::ProtoBuf.ProtoMember(1)]
    private System.Collections.Generic.List<int?>? ProtoId { get => Id; set => Id = value; }

    [global::ProtoBuf.ProtoMember(2)]
    private bool ProtoIsEmptyId
    {
        get => ProtoId?.Count == 0;
        set
        {
            if (value)
                ProtoId = new();
        }
    }
}";

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(IncrementalSourceGenerator), "ProtoEntity.g.cs", SourceText.From(generated.ReplaceLineEndings(CRLF), Encoding.UTF8, SourceHashAlgorithm.Sha1)),
                },
            },
        };

        await test.RunAsync();
    }

    [Fact]
    public async Task NullabeValueTypesProperties()
    {
        var code = @"#nullable enable
namespace Test;
[ProtoBuf.ProtoContract]
public partial class Entity
{
    public int? Id { get; set; }
}";

        var generated = @"// <auto-generated/>
#nullable enable
namespace Test;
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public partial class Entity
{
    [global::ProtoBuf.ProtoMember(1)]
    private int? ProtoId { get => Id; set => Id = value; }
}";

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(IncrementalSourceGenerator), "ProtoEntity.g.cs", SourceText.From(generated.ReplaceLineEndings(CRLF), Encoding.UTF8, SourceHashAlgorithm.Sha1)),
                },
            },
        };

        await test.RunAsync();
    }

    [Fact]
    public async Task ProtoMemberProperty_DoesNotGetGenerated()
    {
        var code = @"namespace Test;

[ProtoBuf.ProtoContract]
public partial class Entity
{   
    [global::ProtoBuf.ProtoMember(1)]
    public int Id { get; set; }
}";

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                },
            },
        };
        await test.RunAsync();
    }

    [Fact]
    public async Task ProtoIgnoreProperty_DoesNotGetGenerated()
    {
        var code = @"namespace Test;

[ProtoBuf.ProtoContract]
public partial class Entity
{   
    [ProtoBuf.ProtoIgnore]
    public int Id { get; set; }
}";

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                },
            },
        };
        await test.RunAsync();
    }

    [Fact]
    public async Task ProtoMemberNumberedProperty_DoesNotGetGenerated()
    {
        var code = @"namespace Test;

[ProtoBuf.ProtoContract]
public partial class Entity
{   
    [global::ProtoBuf.ProtoMember(1)]
    public int Id { get; set; }

    public string Value { get; set; }
}";

        var generated = @"// <auto-generated/>
#nullable enable
namespace Test;
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public partial class Entity
{
    [global::ProtoBuf.ProtoMember(2)]
    private string ProtoValue { get => Value; set => Value = value; }
}";

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(IncrementalSourceGenerator), "ProtoEntity.g.cs", SourceText.From(generated.ReplaceLineEndings(CRLF), Encoding.UTF8, SourceHashAlgorithm.Sha1)),
                },
            },
        };
        await test.RunAsync();
    }

    [Fact]
    public async Task RecordPropertyTest()
    {
        var code = @"namespace Test;

[ProtoBuf.ProtoContract]
public partial record Entity
{
    public int Id { get; set; }
}";

        var generated = @"// <auto-generated/>
#nullable enable
namespace Test;
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public partial record class Entity
{
    [global::ProtoBuf.ProtoMember(1)]
    private int ProtoId { get => Id; set => Id = value; }
}";
        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(IncrementalSourceGenerator), "ProtoEntity.g.cs", SourceText.From(generated.ReplaceLineEndings(CRLF), Encoding.UTF8, SourceHashAlgorithm.Sha1)),
                },
            },
        };
        await test.RunAsync();
    }

    [Fact]
    public async Task StructPropertyTest()
    {
        var code = @"namespace Test;

[ProtoBuf.ProtoContract]
public partial struct Entity
{
    public int Id { get; set; }
}";

        var generated = @"// <auto-generated/>
#nullable enable
namespace Test;
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public partial struct Entity
{
    [global::ProtoBuf.ProtoMember(1)]
    private int ProtoId { get => Id; set => Id = value; }
}";
        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(IncrementalSourceGenerator), "ProtoEntity.g.cs", SourceText.From(generated.ReplaceLineEndings(CRLF), Encoding.UTF8, SourceHashAlgorithm.Sha1)),
                },
            },
        };
        await test.RunAsync();
    }

    [Fact]
    public async Task GlobalNamespaceType_GetsGenerated()
    {
        var code = @"[ProtoBuf.ProtoContract]
public partial class Entity
{
    public int Id { get; set; }
}";

        var generated = @"// <auto-generated/>
#nullable enable
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public partial class Entity
{
    [global::ProtoBuf.ProtoMember(1)]
    private int ProtoId { get => Id; set => Id = value; }
}";
        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(IncrementalSourceGenerator), "ProtoEntity.g.cs", SourceText.From(generated.ReplaceLineEndings(CRLF), Encoding.UTF8, SourceHashAlgorithm.Sha1)),
                },
            },
        };
        await test.RunAsync();
    }

    [Fact]
    public async Task ArrowSyntax_NotGenerated()
    {
        var code = @"[ProtoBuf.ProtoContract]
public partial class Entity
{
    public int Id { get; set; }

    public string Value => ""hi"";
}";

        var generated = @"// <auto-generated/>
#nullable enable
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public partial class Entity
{
    [global::ProtoBuf.ProtoMember(1)]
    private int ProtoId { get => Id; set => Id = value; }
}";
        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(IncrementalSourceGenerator), "ProtoEntity.g.cs", SourceText.From(generated.ReplaceLineEndings(CRLF), Encoding.UTF8, SourceHashAlgorithm.Sha1)),
                },
            },
        };
        await test.RunAsync();
    }

    [Fact]
    public async Task List_GenerateIsEmptyProperty()
    {
        var code = @"#nullable enable
namespace Test;
[ProtoBuf.ProtoContract]
public partial class Entity
{
    public System.Collections.Generic.List<string?> Id { get; set; } = new();
}";

        var generated = @"// <auto-generated/>
#nullable enable
namespace Test;
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public partial class Entity
{
    [global::ProtoBuf.ProtoMember(1)]
    private System.Collections.Generic.List<string?> ProtoId { get => Id; set => Id = value; }

    [global::ProtoBuf.ProtoMember(2)]
    private bool ProtoIsEmptyId
    {
        get => ProtoId?.Count == 0;
        set
        {
            if (value)
                ProtoId = new();
        }
    }
}";

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(IncrementalSourceGenerator), "ProtoEntity.g.cs", SourceText.From(generated.ReplaceLineEndings(CRLF), Encoding.UTF8, SourceHashAlgorithm.Sha1)),
                },
            },
        };

        await test.RunAsync();
    }

    [Fact]
    public async Task IEnumerable_GenerateIsEmptyProperty()
    {
        var code = @"#nullable enable
namespace Test;
[ProtoBuf.ProtoContract]
public partial class Entity
{
    public System.Collections.Generic.IEnumerable<string> Id { get; set; } = System.Linq.Enumerable.Empty<string>();
}";

        var generated = @"// <auto-generated/>
#nullable enable
namespace Test;
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public partial class Entity
{
    [global::ProtoBuf.ProtoMember(1)]
    private System.Collections.Generic.IEnumerable<string> ProtoId { get => Id; set => Id = value; }

    [global::ProtoBuf.ProtoMember(2)]
    private bool ProtoIsEmptyId
    {
        get => ProtoId != null && !System.Linq.Enumerable.Any(ProtoId);
        set
        {
            if (value)
                ProtoId = System.Linq.Enumerable.Empty<string>();
        }
    }
}";

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(IncrementalSourceGenerator), "ProtoEntity.g.cs", SourceText.From(generated.ReplaceLineEndings(CRLF), Encoding.UTF8, SourceHashAlgorithm.Sha1)),
                },
            },
        };

        await test.RunAsync();
    }

    [Fact]
    public async Task HashSet_GenerateIsEmptyProperty()
    {
        var code = @"#nullable enable
namespace Test;
[ProtoBuf.ProtoContract]
public partial class Entity
{
    public System.Collections.Generic.HashSet<string> Id { get; set; } = new();
}";

        var generated = @"// <auto-generated/>
#nullable enable
namespace Test;
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public partial class Entity
{
    [global::ProtoBuf.ProtoMember(1)]
    private System.Collections.Generic.HashSet<string> ProtoId { get => Id; set => Id = value; }

    [global::ProtoBuf.ProtoMember(2)]
    private bool ProtoIsEmptyId
    {
        get => ProtoId?.Count == 0;
        set
        {
            if (value)
                ProtoId = new();
        }
    }
}";

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(IncrementalSourceGenerator), "ProtoEntity.g.cs", SourceText.From(generated.ReplaceLineEndings(CRLF), Encoding.UTF8, SourceHashAlgorithm.Sha1)),
                },
            },
        };

        await test.RunAsync();
    }

    [Fact]
    public async Task Dictionary_GenerateIsEmptyProperty()
    {
        var code = @"#nullable enable
namespace Test;
[ProtoBuf.ProtoContract]
public partial class Entity
{
    public System.Collections.Generic.Dictionary<int, string> Id { get; set; } = new();
}";

        var generated = @"// <auto-generated/>
#nullable enable
namespace Test;
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public partial class Entity
{
    [global::ProtoBuf.ProtoMember(1)]
    private System.Collections.Generic.Dictionary<int, string> ProtoId { get => Id; set => Id = value; }

    [global::ProtoBuf.ProtoMember(2)]
    private bool ProtoIsEmptyId
    {
        get => ProtoId?.Count == 0;
        set
        {
            if (value)
                ProtoId = new();
        }
    }
}";

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(IncrementalSourceGenerator), "ProtoEntity.g.cs", SourceText.From(generated.ReplaceLineEndings(CRLF), Encoding.UTF8, SourceHashAlgorithm.Sha1)),
                },
            },
        };

        await test.RunAsync();
    }

    [Fact]
    public async Task IList_GenerateIsEmptyProperty()
    {
        var code = @"namespace Test;
[ProtoBuf.ProtoContract]
public partial class Entity
{
    public System.Collections.Generic.IList<string> Id { get; set; }
}";

        var generated = @"// <auto-generated/>
#nullable enable
namespace Test;
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public partial class Entity
{
    [global::ProtoBuf.ProtoMember(1)]
    private System.Collections.Generic.IList<string> ProtoId { get => Id; set => Id = value; }

    [global::ProtoBuf.ProtoMember(2)]
    private bool ProtoIsEmptyId
    {
        get => ProtoId?.Count == 0;
        set
        {
            if (value)
                ProtoId = new global::System.Collections.Generic.List<string>();
        }
    }
}";

        var test = new VerifyCS.Test
        {
            TestState =
            {
                Sources = { code },
                GeneratedSources =
                {
                    (typeof(IncrementalSourceGenerator), "ProtoEntity.g.cs", SourceText.From(generated.ReplaceLineEndings(CRLF), Encoding.UTF8, SourceHashAlgorithm.Sha1)),
                },
            },
        };

        await test.RunAsync();
    }
}
