name: Build and Test

on: [push, workflow_dispatch]

env:
  CONFIGURATION: Release
  DOTNET_VERSION: 9.0.x
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        include-prerelease: true
    - name: Build
      run: dotnet build ProtobufSourceGenerator.sln --configuration ${{ env.CONFIGURATION }}
    - name: Test
      run: dotnet test ProtobufSourceGenerator.sln --configuration ${{ env.CONFIGURATION }}