name: Build and Test

on: [push, workflow_dispatch]

env:
  CONFIGURATION: Release
  DOTNET_VERSION: 7.0.x
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        include-prerelease: true
    - name: Build
      run: dotnet build ProtobufSourceGenerator.sln --configuration ${{ env.CONFIGURATION }} --no-self-contained
    - name: Test
      run: dotnet test ProtobufSourceGenerator.sln --configuration ${{ env.CONFIGURATION }}